node {
  checkout scm
  
  stage('Prepare Env') {
    withKubeConfig([credentialsId: 'spark-benchmark-token',
                    serverUrl: "${apiserverurl}"
                   ]) {
      sh "/usr/local/bin/kubectl get pods -n $namespace"
      sh """
         echo "PERFORMING MAPRTICKET GENERATION FOR USER: $mapruser"
         /usr/local/bin/kubectl exec -i tenantcli-0 bash -n $namespace -- bash -c "printf '$mapruser\n$maprpassword\njenkins-secret\nn' | kubernetes/ticketcreator.sh">/dev/null
         sleep 5
         echo "CREATING PVC"
         /usr/local/bin/kubectl apply -f /tmp/spark-benchmark-pvc.yaml -n $namespace
         
         echo "CREATING TEMP POD"
         /usr/local/bin/kubectl apply -f $WORKSPACE/yamls/spark-benchmark-temp-pod.yaml -n $namespace
         sleep 30
        
         echo "COPYING SCRIPTS TO PVC"
         /usr/local/bin/kubectl cp $WORKSPACE/scripts $namespace/spark-benchmark-temp-pod:/spark-benchmark-mount/
         /usr/local/bin/kubectl exec -n $namespace -i spark-benchmark-temp-pod -- mkdir -p spark-benchmark-mount/terragen-files
         /usr/local/bin/kubectl exec -n $namespace -i spark-benchmark-temp-pod -- chmod -R 777 spark-benchmark-mount/terragen-files
      """
    }
  }
  
  stage('Spark Join') {
    withKubeConfig([credentialsId: 'spark-benchmark-token',
                    serverUrl: "${apiserverurl}"
                   ]) {
      sh "/usr/local/bin/kubectl get pods -n $namespace"
      sh """
         export DRIVER_NUMBER_OF_CORES=1
         export EXECUTOR_NUMBER_OF_CORES=1
         export NUMBER_OF_EXECUTOR_INSTANCES=3
         export NUMBER_OF_ROWS_TO_GENERATE=$rowstogenerate
         export JOIN_TYPE=$join_type
         echo "SUBMITTING JOIN SCRIPT"
         /bin/j2 $WORKSPACE/yamls/spark-benchmark-join.yaml > /tmp/spark-benchmark-join.yaml
         /usr/local/bin/kubectl apply -f /tmp/spark-benchmark-join.yaml -n $namespace
         sleep 150
         
         echo "FINISHED JOIN SCRIPT. BENCHMARK TIMES ARE"
         /usr/local/bin/kubectl logs spark-benchmark-join-driver -n $namespace | grep -Po "(\\d*\\.?\\d*) seconds\$"
      """
    }
  }
  
  stage('Spark Terragen Terrasort') {
    withKubeConfig([credentialsId: 'spark-benchmark-token',
                    serverUrl: "${apiserverurl}"
                   ]) {
      sh "/usr/local/bin/kubectl get pods -n $namespace"
      sh """
         echo "SUBMITTING TERRAGEN SCRIPT"
         export DRIVER_NUMBER_OF_CORES=1
         export EXECUTOR_NUMBER_OF_CORES=1
         export NUMBER_OF_EXECUTOR_INSTANCES=3
         export NUMBER_OF_ROWS_TO_GENERATE=$rowstogenerate
         export TERAGEN_OUTPUT_DIR="/spark-benchmark-mount/teragen-files"
         export TERASORT_INPUT_DIR="/spark-benchmark-mount/teragen-files"
         export TERASORT_OUTPUT_DIR="/spark-benchmark-mount/teravalidate-files"
         export TERAVALIDATE_INPUT_DIR="/spark-benchmark-mount/teravalidate-files"
         /bin/j2 $WORKSPACE/yamls/spark-benchmark-terragen.yaml > /tmp/spark-benchmark-terragen.yaml
         /usr/local/bin/kubectl apply -f /tmp/spark-benchmark-terragen.yaml -n $namespace
         sleep 110
         echo "FINISHED TERRAGEN SCRIPT. TIME TO GENERATE $NUMBER_OF_ROWS_TO_GENERATE rows is,"
         /usr/local/bin/kubectl logs spark-benchmark-teragen-driver -n t01 | grep -Po "(\\d*\\.?\\d*) seconds$"
         
         echo "SUBMITTING TERRASORT SCRIPT"
	 /bin/j2 $WORKSPACE/yamls/spark-benchmark-terasort.yaml > /tmp/spark-benchmark-terasort.yaml
         /usr/local/bin/kubectl apply -f /tmp/spark-benchmark-terrasort.yaml -n $namespace
         sleep 150
         echo "FINISHED TERASORT SRIPT. TIME TO SORT $NUMBER_OF_ROWS_TO_GENERATE rows is,"
         /usr/local/bin/kubectl logs spark-benchmark-terasort-driver -n t01 | grep -Po "(\\d*\\.?\\d*) seconds\$"
         
         echo "PERFORMING TERAVALIDATE ON $NUMBER_OF_ROWS_TO_GENERATE ROWS"
	 /bin/j2 $HOME/Spark-Benchmarking/yamls/spark-benchmark-teravalidate.yaml > /tmp/spark-benchmark-teravalidate.yaml
	 /usr/local/bin/kubectl apply -f /tmp/spark-benchmark-teravalidate.yaml -n $namespace
         
         /usr/local/bin/kubectl logs spark-benchmark-teravalidate-driver -n t01 | grep -Po "(\\d*\\.?\\d*) seconds$"
         sleep 150
         echo "FINISHED TERRAVALIDATE. BENCHMARK TIMES ARE"
         /usr/local/bin/kubectl logs spark-benchmark-terrasort-driver -n $namespace | grep -Po "(\\d*\\.?\\d*) seconds\$"
      """
    }
  }
  stage('Cleanup') {
    withKubeConfig([credentialsId: 'spark-benchmark-token',
                    serverUrl: "${apiserverurl}"
                   ]) {
      sh "/usr/local/bin/kubectl get pods -n $namespace"
      sh """
         echo "DELETING SPARK JOIN OPERATOR"
         /usr/local/bin/kubectl delete sparkapplication.sparkoperator.k8s.io spark-benchmark-join -n $namespace

         echo "DELETING SPARK TERRAGEN OPERATOR"
         /usr/local/bin/kubectl delete sparkapplication.sparkoperator.k8s.io spark-benchmark-terragen -n $namespace

         echo "DELETING SPARK TERRASORT OPERATOR"
         /usr/local/bin/kubectl delete sparkapplication.sparkoperator.k8s.io spark-benchmark-terrasort -n $namespace
	 
	 echo "DELETING SPARK TERAVALIDATE OPERATOR"
         /usr/local/bin/kubectl delete sparkapplication.sparkoperator.k8s.io spark-benchmark-teravalidate -n $namespace

         echo "DELETING TEMP POD"
         /usr/local/bin/kubectl delete pod spark-benchmark-temp-pod -n $namespace

         echo "DELETING PVC"
         /usr/local/bin/kubectl delete pvc spark-benchmark-claim -n $namespace

         echo "DELETING MAPR TICKET"
         /usr/local/bin/kubectl delete secret jenkins-secret -n $namespace

         echo "Done .... :)"
      """
    }
  }
}
