node {
  checkout scm
  
  stage('Prepare Env') {
    withKubeConfig([credentialsId: 'spark-benchmark-token',
                    serverUrl: "${apiserverurl}"
                   ]) {
      sh "/usr/local/bin/kubectl get pods -n $namespace"
      sh """
         echo "CREATING PVC"
         /usr/local/bin/kubectl apply -f /tmp/spark-benchmark-pvc.yaml -n $namespace
         
         echo "CREATING TEMP POD"
         /usr/local/bin/kubectl apply -f $WORKSPACE/yamls/spark-benchmark-temp-pod.yaml -n $namespace
         sleep 30
        
         echo "COPYING SCRIPTS TO PVC"
         /usr/local/bin/kubectl cp $WORKSPACE/scripts $namespace/spark-benchmark-temp-pod:/spark-benchmark-mount/
         /usr/local/bin/kubectl exec -n $namespace -i spark-benchmark-temp-pod -- mkdir -p spark-benchmark-mount/terragen-files
         /usr/local/bin/kubectl exec -n $namespace -i spark-benchmark-temp-pod -- chmod -R 777 spark-benchmark-mount/terragen-files
         /usr/local/bin/kubectl delete -f $WORKSPACE/yamls/spark-benchmark-temp-pod.yaml -n $namespace
      """
    }
  }
}
