#
# Copyright 2017 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: "sparkoperator.hpe.com/v1beta2"
kind: SparkApplication
metadata:
  name: spark-benchmark-terasort
spec:
  sparkConf:
    spark.mapr.user.secret: jenkins-secret
    spark.hadoop.fs.dtap.impl: "com.bluedata.hadoop.bdfs.Bdfs"
    spark.hadoop.fs.AbstractFileSystem.dtap.impl: "com.bluedata.hadoop.bdfs.BdAbstractFS"
    spark.hadoop.fs.dtap.impl.disable.cache: "false"
    spark.driver.extraClassPath: "local:///opt/bdfs/bluedata-dtap.jar"
    spark.executor.extraClassPath: "local:///opt/bdfs/bluedata-dtap.jar"
  deps:
    jars:
      - local:///opt/bdfs/bluedata-dtap.jar
  type: Java
  sparkVersion: 2.4.4
  mode: cluster
  image: gcr.io/mapr-252711/spark-2.4.4:202009090453C
  imagePullPolicy: Always
  mainClass: com.github.ehiggs.spark.terasort.TeraSort
  mainApplicationFile: "dtap://TenantStorage/spark-benchmark-1.0.jar"
  restartPolicy:
    type: Never
  volumes:
  - name: spark-benchmark-pv
    persistentVolumeClaim:
      claimName: spark-benchmark-claim
  arguments:
  - "maprfs:///tmp/tera_in_50g"
  - "maprfs:///tmp/terasort_output"
  imagePullSecrets:
  - imagepull
  driver:
    cores: 1
    coreLimit: "1000m"
    memory: "512m"
    labels:
      version: 2.4.4
      hpecp.hpe.com/dtap: hadoop2
  executor:
    cores: 1
    coreLimit: "1000m"
    instances: 3
    memory: "512m"
    labels:
      version: 2.4.4
      hpecp.hpe.com/dtap: hadoop2

