apiVersion: "sparkoperator.hpe.com/v1beta2"
kind: SparkApplication
metadata:
  name: spark-benchmark-join
spec:
  sparkConf:
    spark.mapr.user.secret: jenkins-secret

  type: Java
  sparkVersion: 2.4.5
  mode: cluster
  image: gcr.io/mapr-252711/spark-2.4.5:202010301117C
  imagePullPolicy: Always
  mainApplicationFile: "local:///spark-benchmark-mount/scripts/join_table.py"
  restartPolicy:
    type: Never
  arguments:
  - "{{DF_ROWS_ARGUMENTS}} {{JOIN_TYPE}}"
  imagePullSecrets:
  - imagepull

  volumes:
  - name: spark-benchmark-pv
    persistentVolumeClaim:
      claimName: spark-benchmark-claim

  driver:
    cores: {{DRIVER_NUMBER_OF_CORES}}
    coreLimit: "1000m"
    memory: "512m"
    labels:
      version: 2.4.5
    volumeMounts:
    - name: spark-benchmark-pv
      mountPath: /spark-benchmark-mount

  executor:
    cores: {{EXECUTOR_NUMBER_OF_CORES}}
    coreLimit: "1000m"
    instances: 2
    memory: "512m"
    labels:
      version: 2.4.5
    volumeMounts:
    - mountPath: /spark-benchmark-mount
      name: spark-benchmark-pv
